framework:
    rate_limiter:
        registration:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
        registration_confirm:
            policy: sliding_window
            limit: 15
            interval: '1 hour'
        captcha_challenge:
            policy: sliding_window
            limit: 60
            interval: '1 minute'
        password_reset:
            policy: sliding_window
            limit: 5
            interval: '1 hour'
        password_reset_email:
            policy: sliding_window
            limit: 1
            interval: '1 minute'
        password_reset_confirm:
            policy: sliding_window
            limit: 15
            interval: '1 hour'
