<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261003184914 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Step 1.4: app_user, refresh_token (gesdinet), tree_node.created_by_id NOT NULL (FK RESTRICT)';
    }

    public function up(Schema $schema): void
    {
        // created_by_id e NOT NULL fara valoare implicita: nodurile existente n-au autor.
        // Decizie 1.4: datele de dev se sterg inainte; pe prod nu exista inca noduri.
        $this->abortIf(
            (int) $this->connection->fetchOne('SELECT count(*) FROM tree_node') > 0,
            'tree_node contine noduri fara autor: sterge-le inainte (DELETE FROM tree_node) sau atribuie-le unui utilizator.',
        );

        $this->addSql('CREATE TABLE app_user (id UUID NOT NULL, email VARCHAR(180) NOT NULL, display_name VARCHAR(120) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE refresh_token (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74F2195C74F2195 ON refresh_token (refresh_token)');
        $this->addSql('ALTER TABLE tree_node ADD created_by_id UUID NOT NULL');
        $this->addSql('ALTER TABLE tree_node ADD CONSTRAINT FK_3AFC8272B03A8386 FOREIGN KEY (created_by_id) REFERENCES app_user (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_3AFC8272B03A8386 ON tree_node (created_by_id)');
    }

    public function down(Schema $schema): void
    {
        // Intai FK-ul din tree_node, apoi tabela app_user la care trimite.
        $this->addSql('ALTER TABLE tree_node DROP CONSTRAINT FK_3AFC8272B03A8386');
        $this->addSql('DROP INDEX IDX_3AFC8272B03A8386');
        $this->addSql('ALTER TABLE tree_node DROP created_by_id');
        $this->addSql('DROP TABLE refresh_token');
        $this->addSql('DROP TABLE app_user');
    }
}
